- _academic-curriculum/Home Based Learning (HBL).md
- _for-parents-and-stakeholders/Info for Parents and Students.md
updated on hbl and info for parents
> Update on 16 May

- _about-us/Our Achievements/CCA Achievements.md
- _about-us/collection.yml
- _data/navigation.yml
> Updated CCA Achievements

- _data/navigation.yml
- _join-us/School Corporate Video.md
- index.md
Added FAME link to front page.
> Update Front Page Section

- _the-bedok-viewan-experience/Academic Curriculum/Home Based Learning (HBL).md
> Update for HBL

- _the-bedok-viewan-experience/Academic Curriculum/Home Based Learning (HBL).md
- index.md
> pls review hbl

- _about-us/Our People/School Management Committee.md
- _the-bedok-viewan-experience/Academic Curriculum/Humanities.md
- index.md
Added National Day Celebrations Link
> Updates to website - 11 Aug

- index.md
> Take down notice

- index.md
> Website banner update

- _join-us/BV Open House.md
- _join-us/collection.yml
- index.md
> Nov 9 Review

- index.md
Notice of General Office closure
> Notice Banner

- _join-us/BV Open House.md
> Open House Banner

- index.md
> Notice update

- index.md
> 4.50pm Update

- _for-parents-and-stakeholders/2024 Student's Handbook.md
- _for-parents-and-stakeholders/collection.yml
Added link to 2024 Student's Handbook.
> Student's Handbook

- _for-parents-and-stakeholders/Parent Support Group (PSG).md
> PSG Page update

- _for-parents-and-stakeholders/Info for Parents and Students.md
> CCA Option Link

- _for-parents-and-stakeholders/Secondary One CCA Option.md
> Sec 1 CCA Option Update

- _cca/Clubs/Infocomm Club.md
- _cca/Sports/Athletics (Boys & Girls).md
- _cca/Sports/Badminton (Boys).md
- _cca/Sports/Football (Boys).md
- _cca/Uniformed Groups/National Cadet Corps (NCC) Boys and Girls.md
> CCA Schedule Update

- _config.yml
- _data/footer.yml
- _join-us/Direct School Admission (DSA).md
- index.md
> DSA Updates

- _join-us/Direct School Admission (DSA).md
> DSA Page updates

- pages/privacy.md
- pages/terms-of-use.md
Updated Privacy Statement and Terms of Use
> Privacy and Terms

- _about-us/Our People/Form Teachers (Sec 1).md
- _about-us/Our People/Form Teachers (Sec 2).md
- _about-us/Our People/Form Teachers (Sec 3).md
- _about-us/Our People/Form Teachers (Sec 4 & 5).md
- pages/terms-of-use.md
Changes to the Form Teachers List for Semester 2.
> FT Updates

- index.md
> Taking down notice

- index.md
> Notice taken down

- _about-us/Our Achievements & Highlights/Highlights of the Year.md
- _cca/Clubs/Infocomm Club.md
- _cca/Performing Arts/Concert Band.md
- _cca/Performing Arts/Guzheng Ensemble.md
- _cca/Sports/Badminton (Boys).md
- _cca/Uniformed Groups/Girl Guides.md
> Highlights of the Year

- _about-us/Our Achievements & Highlights/Character Awards.md
- _cca/Performing Arts/Choir.md
- _cca/Performing Arts/English Drama.md
- _cca/Performing Arts/Modern Dance.md
- _cca/Sports/Football (Boys).md
- _cca/Sports/Netball (Girls).md
- _cca/Uniformed Groups/National Police Cadet Corps (NPCC) Boys.md
- _the-bedok-viewan-experience/Academic Curriculum/National Digital Literacy Programme (NDLP).md
> Website Update - Oct 3

- index.md
> Banner update

- index.md
> Website Update

- _join-us/Secondary 1 (2025) Registration.md
> S1 Page update

- _about-us/Our People/Form Teachers (Sec 1).md
- _join-us/Secondary 1 (2025) Registration.md
> Updates to FTs

- _cca/Clubs/Service Learning Club.md
> Update to SLC page

- _for-parents-and-stakeholders/Info on Device Management Application (DMA).md
> Removal of duplicate link

- _for-parents-and-stakeholders/Info for Parents and Students.md
> Update 14 March

- _about-us/Our People/Form Teachers (Sec 1).md
- _about-us/Our People/Form Teachers (Sec 2).md
- _join-us/Direct School Admission (DSA).md
- index.md
> Update to DSA

- _about-us/Our Achievements & Highlights/Highlights of the Year.md
- index.md
> Website Notice

- index.md
> Notice Removal

- index.md
> Website Notice Taken Down
